services:
  - type: web
    name: telegram-otp-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y firefox-esr
      pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISPLAY
        value: ":99"
    healthCheckPath: /health
    autoDeploy: false